
@baseUrl =  http://localhost:4000/contest

GET {{baseUrl}}/getContest/product_id/product_id
###

GET {{baseUrl}}/getContests/id
###

GET {{baseUrl}}/getContestAll
###

GET {{baseUrl}}/getOneWithProduct/con_243636b913cf
###

GET {{baseUrl}}/getHistory
###


GET {{baseUrl}}/getContestsSoldout
###


GET {{baseUrl}}/getMyOrders/25
###

POST {{baseUrl}}/createContest
Content-Type: application/json

{
"con_id": "3",
"product_id": "product_id",
"con_status": "con_status",
"con_total_spots":"0",
"con_spots" : "300",
"con_startdate": "2022-12-31T10:41",
"con_enddate": "2022-12-31T10:41",
"con_win": "con_win",
"con_discription": "con_discription",
"con_thumbnails": "con_thumbnails",
"con_winner": "con_winner",
"con_winnerCoupen": "con_winnerCoupen"
}
###

POST {{baseUrl}}/updateContest
Content-Type: application/json

{
"id": "2",
"con_status": "completed"
}
###

DELETE   {{baseUrl}}/deleteContest
Content-Type: application/json

{
"id": "2"
}


###

POST {{baseUrl}}/updateQuantity/ordr_02cd2a6a1699
Content-Type: application/json

{
    "quantity": "5"
}
###
POST {{baseUrl}}/goToPayment/2
Content-Type: application/json

{
    "id": "2",
    "order_status": "shipped"
}
###


GET {{baseUrl}}/getMyOrders/usr_5afd1340dded/oncart
### /user_id/order_status


POST {{baseUrl}}/setWinner
Content-Type: application/json

{
    "winner": "usr_5afd1340dded",
    "winnerCoupen": "coup_43abb56fb267",
    "contest_id": "con_1488635dc693"
}
###



GET {{baseUrl}}/getHistory
###

