
@baseUrl =  http://localhost:4000/user

GET {{baseUrl}}/getUser/username/amir
###

GET {{baseUrl}}/getUsers/username
###

GET {{baseUrl}}/getMyAddress/usr_5afd1340dded
###

POST {{baseUrl}}/addUser
Content-Type: application/json

{
"id": "25",
"user_id": "user1",
"username" : "amir test",
"fullname" : "test filed",
"user_password" : "test filed",
"mobile" : "test filed"
}


###

POST {{baseUrl}}/updateUser/users
Content-Type: application/json

{
"id": "25",
"username" : "amir",
"fullname" : "test filed",
"user_password" : "test filed",
"mobile" : "test filed"
}

###

DELETE   {{baseUrl}}/deleteData/users
Content-Type: application/json

{
"id": "25"
}

###
POST {{baseUrl}}/addToRefferal
Content-Type: application/json

{
"ref_id" : "refidh87",
"user_id" : "usr_dfsdf",
"ref_status" : "pending",
"entry_date" : "2022-05-05"
}

