
@baseUrl =  http://localhost:4000/user
# @baseUrl =  https://coupen.herokuapp.com/user


GET {{baseUrl}}/getUser/username/amir
###

GET {{baseUrl}}/getUsers/username
###

GET {{baseUrl}}/getMyAddress/usr_5afd1340dded
###

POST {{baseUrl}}/addUser
Content-Type: application/json

{
"id": "25",
"user_id": "user1",
"username" : "amir test",
"fullname" : "test filed",
"user_password" : "test filed",
"mobile" : "test filed"
}


###

POST {{baseUrl}}/updateUser/users
Content-Type: application/json

{
"id": "25",
"username" : "amir",
"fullname" : "test filed",
"user_password" : "test filed",
"mobile" : "test filed"
}

###

DELETE   {{baseUrl}}/deleteData/users
Content-Type: application/json

{
"id": "25"
}

###
POST {{baseUrl}}/addToRefferal
Content-Type: application/json

{
"ref_id" : "refidh87",
"user_id" : "usr_dfsdf",
"ref_status" : "pending",
"entry_date" : "2022-05-05"
}


### wishlist

POST {{baseUrl}}/addToWishList
Content-Type: application/json

{
"con_id" : "con_d5eee96e237a",
"user_id" : "usr_20e104abc603"
}

### remove from wishlist
DELETE  {{baseUrl}}/removeFromWishList
Content-Type: application/json

{
"item_id" : 1
}


### get user wishlist
GET  {{baseUrl}}/getWishLists/usr_20e104abc603


### update level
POST   {{baseUrl}}/updateLevel
Content-Type: application/json

{
"price": 255,
"user_id" : "usr_20e104abc603"
}



### get staff
GET {{baseUrl}}/getStaff/usr_admin


### get is user exists
GET {{baseUrl}}/isUserExists/ammar

### reset password
POST   {{baseUrl}}/resetPassword
Content-Type: application/json

{
"user_id" : "usr_20e104abc603",
"email" : "ammarvady@gmail.com"
}


### STRIPE INTENT
POST   {{baseUrl}}/paymentIntent
Content-Type: application/json

{
    "amount": 2
}

### STRIPE INTENT CONFIRM
POST   {{baseUrl}}/paymentIntentConfirm
Content-Type: application/json

{
    "intent_id": "id_fg",
    "order_ids": ["ordr_56a44d5bda00", "ordr_56a44d5bda02"],
    "contest_ids": ["con_56a44d5bda00", "con_56a44d5bda02"]
}

### STRIPE INTENT CONFIRM
POST   {{baseUrl}}/paymentIntentConfirm
Content-Type: application/json

{
    "intent_id": "id_fg"
}




